version: '3'

services:
  mongo_db:
    container_name: database_container
    mem_limit: 1024m 
    cpus: '1' 
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    container_name: backend_container
    mem_limit: 1024m 
    cpus: '1' 
    build: .
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      MONGO_URL: mongodb://mongo_db:27017/certipulse
      SECRET_TOKEN: certipulse1071
      EMAIL_ADRESS: certificateme.info@gmail.com
      PASSWORD: czpq femr utsz digk
    
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
